### ISSUE TITLE
Code design review

### ISSUE THREAD

**Issue by SamaraFellaDina** [yujing-student/user-experience-enhanced-website#3]
### [`server.js`](https://github.com/yujing-student/user-experience-enhanced-website/blob/main/server.js)

* Ik zie dat je hier veel `console.log` staat, misschien wanneer je het helemaal af hebt dit even weghalen. 
https://github.com/yujing-student/user-experience-enhanced-website/blob/c724915d717081a911ec13c13e2f96bed311ebaf/server.js#L158-L162

### [`head.ejs`](https://github.com/yujing-student/user-experience-enhanced-website/blob/main/views/partials/head.ejs#L2)

* Ik zou deze even op `lang=nl` zetten
https://github.com/yujing-student/user-experience-enhanced-website/blob/c724915d717081a911ec13c13e2f96bed311ebaf/views/partials/head.ejs#L2

* Zou een `class` hierop nodig zijn?
https://github.com/yujing-student/user-experience-enhanced-website/blob/c724915d717081a911ec13c13e2f96bed311ebaf/views/partials/head.ejs#L21

### [`index.ejs`](https://github.com/yujing-student/user-experience-enhanced-website/blob/main/views/index.ejs#L2)
* Het valt me op dat je veel gebruik maakt van classes, ik zou kijken of het wellicht nodig is om zoveel classes nodig zijn om aan te roepen. 
https://github.com/yujing-student/user-experience-enhanced-website/blob/c724915d717081a911ec13c13e2f96bed311ebaf/views/index.ejs#L2
* Je hebt een `h2` element, maar geen `h1`

### [`style.css`](https://github.com/yujing-student/user-experience-enhanced-website/blob/main/public/style/style.css)

* Je hebt goede css geschreven ik zie alleen dat je veel gebruik maakt van classes. Je zou meer DRY kunnen werken, waarbij je eerst de basiselementen kunnen aanroepen, zo voorkom je dat je verschillende lijnen met tekst meerdere keren aanroept.

![](https://media.giphy.com/media/vVzH2XY3Y0Ar6/giphy.gif?cid=82a1493bcrzuseil6jb0jvy85tmwoac24g3ed8rnzwafq06d&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

**Comment by yujing-student** [comment]
ik heb de issues gelezen en ben er mee aan de slag gegaan
